handy_helper_2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('taskManager.urls')),
]

taskManager/urls.py
from . import views
from django.urls import path

app_name = "taskManager"

urlpatterns = [
    path('', views.index, name="index"),
    path('register', views.register, name="register"),
    path('login', views.login, name="login"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('jobs/new', views.newJobForm, name="newJobForm"),
    path('jobs/new/add', views.addJob, name="addJob"),
    path('jobs/view/<int:taskID>', views.viewTask, name="viewTask"),
    path('jobs/remove/<int:taskID>', views.removeTaskForm, name="removeTaskForm"),
    path('jobs/remove/<int:taskID>/remove', views.removeTask, name="removeTask"),
    path('jobs/edit/<int:taskID>', views.editTaskForm, name="editTaskForm"),
    path('jobs/edit/<int:taskID>/edit', views.editTask, name="editTask"),
    path('jobs/claim/<int:taskID>', views.claimTask, name="claimTask"),
    path('jobs/complete/<int:taskID>', views.completeTask, name="completeTask"),
    path('jobs/release/<int:taskID>', views.releaseTask, name="releaseTask"),
    path('logout', views.logout, name="logout"),
]

taskManager/models.py
from django.db import models
import re

# Create your models here.
class UserManager(models.Manager):
    def registrationValidator(self, postData):
        errors = {}
        EMAIL_REGREX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if len(postData['firstName']) < 2:
            errors['firstName'] = "First Name should be at least 2 characters!"
        if len(postData['lastName']) < 2:
            errors['lastName'] = "Last Name should be at least 2 characters!"
        if not EMAIL_REGREX.match(postData['email']):
            errors['email'] = "Invalid email address!"
        if len(User.objects.filter(email=postData['email'])) > 0:
            errors['email'] = "Invalid email - user already exists!"
        if len(postData['password']) < 8:
            errors['password'] = "Password must be at least 8 characters!"
        if postData['password'] != postData['passwordConfirm']:
            errors['passwordConfirm'] = "Password does not match!"
        return errors
        
    def loginValidator(self, postData):
        errors = {}
        EMAIL_REGREX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGREX.match(postData['email']):
            errors['email'] = "Invalid email address!"
        if len(User.objects.filter(email=postData['email'])) < 1:
            errors['email'] = "Invalid email address - user does not exist. Please register!"
        if len(postData['password']) < 8:
            errors['password'] = "Password must be at least 8 characters!"
        return errors

    def userInfoValidator(self, postData):
        errors = {}
        EMAIL_REGREX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGREX.match(postData['email']):
            errors['email'] = "Invalid email address!"
        if len(postData['firstName']) < 2:
            errors['firstName'] = "Invalid First Name!"
        if len(postData['lastName']) < 2:
            errors['lastName'] = "Invalid Last Name!"
        return errors

    def userPasswordValidator(self, postData):
        errors = {}
        if len(postData['password']) < 8:
            errors['password'] = "Password must be at least 8 characters!"
        return errors

class TaskManager(models.Manager):
    def inputValidator(self,postData):
        errors = {}

        if len(postData['title']) < 3:
            errors['title'] = "Task Title should be at least 3 characters!"
        if len(postData['title']) == 0:
            errors['title'] = "Task Title must be provided!"
        if len(postData['desc']) < 3:
            errors['desc'] = "Task Description should be at least 3 characters!"
        if len(postData['desc']) == 0:
            errors['desc'] = "Task Description must be provided!"
        if len(postData['location']) < 3:
            errors['location'] = "Task Location should be at least 3 characters!"
        if len(postData['location']) == 0:
            errors['location'] = "Task Location must be provided!"
        
        return errors

class CategoryManager(models.Manager):
    def inputValidator(self,postData):
        errors = {}
        inPostData = False
        for category in Category.objects.all():
            if category.title in postData:
                inPostData = True
        
        print(inPostData)
        print(postData)
        if inPostData==False and postData['categoryOther']=="":
            errors['category'] = "Please select a category or enter a new one!"

        return errors

class User(models.Model):
    firstName = models.CharField(max_length=255)
    lastName = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    password = models.CharField(max_length=255)
    objects = UserManager()
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    #tasksAdded = tasks that the User has added
    #tasksOwned = tasks that the User has said they would do 

class Category(models.Model):
    title = models.CharField(max_length=255)
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    objects = CategoryManager()
    #tasksAssociated = tasks associated with the category

    def __str__(self):
        return f"Category title: {self.title}"

class Task(models.Model):
    title = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    createdAt = models.DateTimeField(auto_now_add=True)
    updatedAt = models.DateTimeField(auto_now=True)
    addedBy = models.ForeignKey(User, related_name="tasksAdded", on_delete=models.CASCADE)
    objects = TaskManager()
    owner = models.ForeignKey(User, related_name="tasksOwned", on_delete=models.CASCADE, null=True)
    categories = models.ManyToManyField(Category, related_name="tasksAssociated", null=False)
    isCompleted = models.BooleanField(default=False)
    #isCompleted = boolean field (black belt)
    #owner = foreign key user object (black belt)
    #categories = categories that the task falls under, many to many field (black belt)

    def __str__(self):
        return f"Task Owner: {self.owner}"

taskManager/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import User, Task, Category
import bcrypt

# Create your views here.
def index(request):
    return render(request, "loginPage.html")

def login(request):
    errors = User.objects.loginValidator(request.POST)
    if len(errors) > 0:
        for key,value in errors.items():
            messages.error(request, value)
        return redirect("taskManager:index")
    else:
        loggedUser = User.objects.filter(email=request.POST["email"])[0]
        if bcrypt.checkpw(request.POST['password'].encode(), loggedUser.password.encode()):
            request.session["userID"] = loggedUser.id
            return redirect("taskManager:dashboard")
        else:
            messages.error(request, "Incorrect password - please try again!")
            return redirect("taskManager:index")

def register(request):
    errors = User.objects.registrationValidator(request.POST)
    if len(errors)>0:
        for key,value in errors.items():
            messages.error(request,value)
        return redirect("taskManager:index")
    else:
        password = request.POST['password']
        pwHash = bcrypt.hashpw(password.encode(), bcrypt.gensalt()).decode()
        newUser = User.objects.create(
            firstName = request.POST['firstName'],
            lastName = request.POST['lastName'],
            email = request.POST['email'],
            password = pwHash
        )
        request.session['userID'] = newUser.id
        messages.success(request, "Thanks for joining us!")
        return redirect("taskManager:dashboard")

def dashboard(request):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    loggedUser = User.objects.get(id=request.session['userID'])
    context = {
        "loggedUser" : loggedUser,
        "tasks": Task.objects.order_by("-createdAt"),
    }
    return render(request, "dashboard.html", context)

def newJobForm(request):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    loggedUser = User.objects.get(id=request.session['userID'])
    context = {
        "loggedUser":loggedUser,
        "categories":Category.objects.all(),
    }
    return render(request, "newJobForm.html", context)

def addJob(request):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    errors = Task.objects.inputValidator(request.POST)
    errors2 = Category.objects.inputValidator(request.POST)
    if len(errors)>0 or len(errors2)>0:
        for key,value in errors.items():
            messages.error(request,value)
        for key,value in errors2.items():
            messages.error(request,value)
        return redirect("taskManager:newJobForm")
    else:
        newTask = Task.objects.create(
            title = request.POST['title'],
            desc = request.POST['desc'],
            location = request.POST['location'],
            addedBy = User.objects.get(id=request.session['userID']),
        )

        for cat in Category.objects.all():
            if cat.title in request.POST:
                newTask.categories.add(Category.objects.get(title=cat.title))
        if request.POST['categoryOther'] != "":
            newCat = Category.objects.create(
                title=request.POST['categoryOther']
            )
            newTask.categories.add(newCat)

        messages.success(request, f"Task \"{newTask.title}\" Added!")
        return redirect("taskManager:dashboard")

def viewTask(request, taskID):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    loggedUser = User.objects.get(id=request.session['userID'])
    context = {
        "loggedUser":loggedUser,
        "task": Task.objects.get(id=taskID),
    }
    return render(request, "viewJob.html", context)

def removeTaskForm(request, taskID):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    loggedUser = User.objects.get(id=request.session['userID'])
    context = {
        "loggedUser":loggedUser,
        "task": Task.objects.get(id=taskID),
    }
    return render(request, "removeJobForm.html", context)

def removeTask(request, taskID):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    taskToBeDeleted = Task.objects.get(id=taskID)
    title = taskToBeDeleted.title
    taskToBeDeleted.delete()
    messages.success(request, f"Task \"{title}\" deleted!")
    return redirect("taskManager:dashboard")

def editTaskForm(request, taskID):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    loggedUser = User.objects.get(id=request.session['userID'])
    context = {
        "loggedUser":loggedUser,
        "task": Task.objects.get(id=taskID),
        "categories": Category.objects.all(),
    }
    return render(request,"editJobForm.html", context)

def editTask(request, taskID):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    errors = Task.objects.inputValidator(request.POST)
    errors2 = Category.objects.inputValidator(request.POST)
    if len(errors)>0 or len(errors2):
        for key,value in errors.items():
            messages.error(request,value)
        for key,value in errors2.items():
            messages.error(request,value)
        return redirect("taskManager:editTaskForm", taskID=taskID)
    else:
        currentTask = Task.objects.get(id=taskID)
        currentTask.title = request.POST['title']
        currentTask.desc = request.POST['desc']
        currentTask.location = request.POST['location']

        for cat in Category.objects.all():
            if cat.title in request.POST:
                currentTask.categories.add(Category.objects.get(title=cat.title))
            else:
                currentTask.categories.remove(Category.objects.get(title=cat.title))
        if request.POST['categoryOther'] != "":
            newCat = Category.objects.create(
                title=request.POST['categoryOther']
            )
            currentTask.categories.add(newCat)

        currentTask.save()
        messages.success(request, f"Task \"{currentTask.title}\" modified!")
        return redirect("taskManager:dashboard")

def claimTask(request, taskID):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    currentTask = Task.objects.get(id=taskID)
    loggedUser = User.objects.get(id=request.session['userID'])
    currentTask.owner = loggedUser
    currentTask.save()
    messages.success(request, f"Task \"{currentTask.title}\" claimed!")
    return redirect("taskManager:dashboard")

def completeTask(request, taskID):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    currentTask = Task.objects.get(id=taskID)
    loggedUser = User.objects.get(id=request.session['userID'])
    currentTask.delete()
    # currentTask.isComplete = True
    # currentTask.save()
    messages.success(request, f"Task \"{currentTask.title}\" completed!")
    return redirect("taskManager:dashboard")

def releaseTask(request, taskID):
    if 'userID' not in request.session:
        messages.error(request, "Please log in or register first!")
        return redirect('taskManager:index')
    currentTask = Task.objects.get(id=taskID)
    loggedUser = User.objects.get(id=request.session['userID'])
    currentTask.owner = None
    # currentTask.isComplete = True
    # currentTask.save()
    currentTask.save()
    messages.success(request, f"Task \"{currentTask.title}\" released!")
    return redirect("taskManager:dashboard")

def logout(request):
    request.session.clear()
    messages.success(request, "Successfully Logged Out")
    return redirect("taskManager:index")

taskManager/templates/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>User Dashboard!</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h2 class="col">Hello {{loggedUser.firstName}}!</h2>
            <a class="col-2" href={% url 'taskManager:logout' %}>Logout</a>
            <form>
                <button class="btn btn-primary" formaction={% url 'taskManager:newJobForm' %}>New Job!</button
            </form>
        </div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p class="alert alert-danger role=alert">{{ message }}</p>
                {% elif message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                    <p class="alert alert-success role=alert">{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
        <div class="row">
            <h2 class="col">Everyone's Jobs</h2>
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">Job</th>
                        <th scope="col">Location</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for task in tasks %}
                        {% if task.owner == null %}
                        <tr scope="row">
                            <td>{{task.title}}</td>
                            <td>{{task.location}}</td>
                            <td>
                                <a class="col" href={% url 'taskManager:viewTask' taskID=task.id %}>View</a>
                                {% if task.addedBy.id == loggedUser.id %}
                                    <a class="col" href={% url 'taskManager:removeTaskForm' taskID=task.id %}>Remove</a>
                                    <a class="col" href={% url 'taskManager:editTaskForm' taskID=task.id %}>Edit</a>
                                {% endif %}
                                <a class="col" href={% url 'taskManager:claimTask' taskID=task.id %}>Claim</a>
                            </td>
                        </tr>
                        {% endif %}
                    {% endfor %}
                <tbody>
            </table>
        </div>
        <div class="row">
            <h2 class="col">{{loggedUser.firstName}}'s Jobs</h2>
            <table class="table">
                <tr>
                    <th>Job</th>
                    <th>Actions</th>
                </tr>
                {% for task in loggedUser.tasksOwned.all %}
                    <tr>
                        <td>{{task.title}}</td>
                        <td>
                            <a class="col" href={% url 'taskManager:viewTask' taskID=task.id %}>View</a>
                            <a class="col" href={% url 'taskManager:completeTask' taskID=task.id %}>Done</a>
                            <a class="col" href={% url 'taskManager:releaseTask' taskID=task.id %}>Give Up</a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</body>
</html>

taskManager/templates/editJobForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Handy Helper 2!</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h2 class="col">Hello {{loggedUser.firstName}}! Let's edit your job!</h2>
            <a class="col-2" href={% url 'taskManager:logout' %}>Logout</a>
        </div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p class="alert alert-danger role=alert">{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
        <div class="row">
            <form class="col-6" action={% url 'taskManager:register' %} method="POST">    
                <h2 class="row">Editing Job "{{task.title}}"</h2>
                {% csrf_token %}
                <div class="form-group row">
                    <label for="title" class="col-form-label">Title:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="title" value="{{task.title}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="desc" class="col-form-label">Description:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="desc" value="{{task.desc}}">
                    </div>
                </div>
                <div class="form-group row">
                    <label for="location" class="col-form-label">Location:</label>
                    <div class="col-sm-6">
                        <input type="text" class="form-control" name="location" value="{{task.location}}">
                    </div>
                </div>
                <div class="form-group row">
                    Category:
                    <div class="col">
                        {% for category in categories %}
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="{{category.title}}" {% if category in task.categories.all %}checked{% endif %}>
                                <label for="{{category.title}}" class="form-check-label">{{category.title}}</label>
                            </div>
                        {% endfor %}
                        <div class="form-group row">
                            <label for="categoryOther">Other:</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" name="categoryOther">
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit" formaction={% url 'taskManager:editTask' taskID=task.id %}>Submit</button>
                <button class="btn btn-primary" type="submit" formaction={% url 'taskManager:dashboard' %}>Cancel</button>
            </form>
        </div>
    </div>
</body>
</html>

taskManager/templates/newJobForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Handy Helper 2!</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h2 class="col">Hello {{loggedUser.firstName}}! Create a job!</h2>
            <a class="col-2" href={% url 'taskManager:logout' %}>Logout</a>
        </div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p class="alert alert-danger role=alert">{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
        <div class="row">
            <form class="col-6" action={% url 'taskManager:register' %} method="POST">
                <h2 class="row">Add New Job</h2>
                {% csrf_token %}
                <div class="form-group row">
                    <label class="form-label col-form-label" for="title">Title:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control " name="title">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="form-label col-form-label" for="desc">Description:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="desc">
                    </div>
                </div>
                <div class="form-group row">
                    <label class="form-label col-form-label" for="location">Location:</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" name="location">
                    </div>
                </div>
                <div class="form-group row">
                    Category:
                    <div class="col">
                        {% for category in categories %}
                            <div class="form-check">
                                <input type="checkbox" class="form-check-input" name="{{category.title}}">
                                <label for="{{category.title}}" class="form-check-label">{{category.title}}</label>
                            </div>
                        {% endfor %}
                        <div class="form-group row">
                            <label for="categoryOther">Other:</label>
                            <div class="col-sm-4">
                                <input type="text" class="form-control" name="categoryOther">
                            </div>
                        </div>
                    </div>
                </div>
                <button class="btn btn-primary" type="submit" formaction={% url 'taskManager:addJob' %}>Submit</button>
                <button class="btn btn-primary" type="submit" formaction={% url 'taskManager:dashboard' %}>Cancel</button>
            </form>
        </div>
    </div>
</body>
</html>

taskManager/templates/removeJobForm.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Handy Helper 2!</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h2 class="col">Hello {{loggedUser.firstName}}! You're currently trying to remove a job!</h2>
            <a class="col-2" href={% url 'taskManager:logout' %}>Logout</a>
        </div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p class="alert alert-danger role=alert">{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
        <div class="row">
            <form class="col-6" action={% url 'taskManager:register' %} method="POST">
                {% csrf_token %}
                <h2>Are you sure you want to remove the below job?</h2>
                <h3>Job Title: "{{task.title}}"</h3>
                <ul>
                    <li>{{task.desc}}</li>
                    <li>Location: {{task.location}}</li>
                    <li>Posted by: {{task.addedBy.firstName}}</li>
                    <li>Posted on: {{task.createdAt}}</li>
                    <li>
                        Categories: {% for category in task.categories.all %}{{category.title}} | {% endfor %}
                    </li>
                </ul>
                <button class="btn btn-primary" type="submit" formaction={% url 'taskManager:removeTask' taskID=task.id %}>Submit</button>
                <button class="btn btn-primary" type="submit" formaction={% url 'taskManager:dashboard' %}>Cancel</button>
            </form>
        </div>
    </div>
</body>
</html>

taskManager/templates/viewJob.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Handy Helper 2!</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <h2 class="col">Hello {{loggedUser.firstName}}! These are the job details!</h2>
            <a class="col-2" href={% url 'taskManager:dashboard' %}>Dashboard</a>
            <a class="col-2" href={% url 'taskManager:logout' %}>Logout</a>
        </div>
        {% if messages %}
            {% for message in messages %}
                {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <p class="alert alert-danger role=alert">{{ message }}</p>
                {% endif %}
            {% endfor %}
        {% endif %}
        <h2>{{task.title}}</h2>
        <ul>
            <li>Description: {{task.desc}}</li>
            <li>Location: {{task.location}}</li>
            <li>Posted by: {{task.addedBy.firstName}}</li>
            <li>Posted on: {{task.createdAt}}</li>
            <li>
                Categories: {% for category in task.categories.all %}{{category.title}} | {% endfor %}
            </li>
        </ul>
        {% if task.owner.id != loggedUser.id %}
            <a class="col" href={% url 'taskManager:claimTask' taskID=task.id %}>Claim Task</a>
        {% endif %}
        {% if task.owner.id == loggedUser.id %}
            <a class="col" href={% url 'taskManager:releaseTask' taskID=task.id %}>Give Up Task</a>
        {% endif %}
    </div>
</body>
</html>